

CREATE TABLE `dept_tbl` (
  `dept_id` int(15) NOT NULL AUTO_INCREMENT,
  `block_name` varchar(200) NOT NULL,
  `dept_name` varchar(200) NOT NULL,
  `room_name` varchar(200) NOT NULL,
  `room_no` int(15) NOT NULL,
  PRIMARY KEY (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






CREATE TABLE `issue_tbl` (
  `sno` int(15) NOT NULL AUTO_INCREMENT,
  `dept_id` int(15) NOT NULL,
  `item_id` int(15) NOT NULL,
  `unit_id` int(15) NOT NULL,
  `unitsissued` int(15) NOT NULL,
  `noofitems` int(15) NOT NULL,
  `indentno` varchar(200) NOT NULL,
  `voucherno` varchar(200) NOT NULL,
  `issueddate` date NOT NULL,
  PRIMARY KEY (`sno`),
  KEY `dept_id` (`dept_id`),
  KEY `item_id` (`item_id`),
  KEY `unit_id` (`unit_id`),
  CONSTRAINT `issue_tbl_ibfk_1` FOREIGN KEY (`dept_id`) REFERENCES `dept_tbl` (`dept_id`),
  CONSTRAINT `issue_tbl_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `item_tbl` (`item_id`),
  CONSTRAINT `issue_tbl_ibfk_3` FOREIGN KEY (`unit_id`) REFERENCES `unit_tbl` (`unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






CREATE TABLE `item_tbl` (
  `item_id` int(15) NOT NULL AUTO_INCREMENT,
  `item_name` varchar(200) NOT NULL,
  PRIMARY KEY (`item_id`)
) ENGINE=InnoDB AUTO_INCREMENT=718 DEFAULT CHARSET=latin1;

INSERT INTO item_tbl VALUES("1","ADJUSTABLE SPANNER");
INSERT INTO item_tbl VALUES("2","ADMISSION & DISCHARGE REGISTER");
INSERT INTO item_tbl VALUES("3","ADSON FORCEPS 5 INCH NON-TOOTHED");
INSERT INTO item_tbl VALUES("4","ADSON FORCEPS 5 INCH TOOTHED");
INSERT INTO item_tbl VALUES("5","AEROTER");
INSERT INTO item_tbl VALUES("6","AIR BED (ANTI-DECUBITUS)");
INSERT INTO item_tbl VALUES("7","AIR COOLER IRON");
INSERT INTO item_tbl VALUES("8","AIR KEY PLUGS");
INSERT INTO item_tbl VALUES("9","AIROTARY SPRAY");
INSERT INTO item_tbl VALUES("10","AIROTOR");
INSERT INTO item_tbl VALUES("11","AIROTOR CATRIDGE");
INSERT INTO item_tbl VALUES("12","AJANTA WALL CLOCKS");
INSERT INTO item_tbl VALUES("13","ALBERT STAIN");
INSERT INTO item_tbl VALUES("14","ALBUMIN KIT");
INSERT INTO item_tbl VALUES("15","ALGINATE SPATULA");
INSERT INTO item_tbl VALUES("16","ALIGANATE");
INSERT INTO item_tbl VALUES("17","ALLIES FORCEPS 6 INCH");
INSERT INTO item_tbl VALUES("18","ALLIES FORCEPS 8 INCH");
INSERT INTO item_tbl VALUES("19","ALLUMINIUM ANDOIZED SCREW BOX WITH S.S TRAY 3");
INSERT INTO item_tbl VALUES("20","ALLUMINIUM SCREW BOX 4.0MM X 6.5MM");
INSERT INTO item_tbl VALUES("21","ALLUMINIUM SCREW BOX 4.5MM");
INSERT INTO item_tbl VALUES("22","ALMERAH 8 LOCKER");
INSERT INTO item_tbl VALUES("23","ALMERAH IRON");
INSERT INTO item_tbl VALUES("24","ALP KIT (ALKALINE POSPHATE)");
INSERT INTO item_tbl VALUES("25","AMALGARY CAVIES");
INSERT INTO item_tbl VALUES("26","AMBU BAG WITH MASK (ADULT)");
INSERT INTO item_tbl VALUES("27","AMBU BAG WITH MASK (PAEDITRIC)");
INSERT INTO item_tbl VALUES("28","AMBUBAG SILICON ADULT");
INSERT INTO item_tbl VALUES("29","AMBUBAG SILICON NEONATAL");
INSERT INTO item_tbl VALUES("30","AMMONIA SOLUTION");
INSERT INTO item_tbl VALUES("31","001 CASE SHEET");
INSERT INTO item_tbl VALUES("32","002 OP CARDS");
INSERT INTO item_tbl VALUES("33","003 PRESCRIPTION PAD");
INSERT INTO item_tbl VALUES("34","004 PHARMACY PRESCRIPTION PAD");
INSERT INTO item_tbl VALUES("35","005 X-RAY & E C G / U.S REQUISITION");
INSERT INTO item_tbl VALUES("36","006 LAB REQUISITION (ULTRASOUND SCAN)");
INSERT INTO item_tbl VALUES("37","007 LAB REQUISITION (HAEMATOLOGY & MICROBIOLO");
INSERT INTO item_tbl VALUES("38","008 DEPARTMENT OF BIOCHEMISTRY (ALL REPORTs)");
INSERT INTO item_tbl VALUES("39","009 DEPARTMENT OF MICROBIOLOGY (CULTURE REPOR");
INSERT INTO item_tbl VALUES("40","010 FLUID FOR BIOCHEMICAL AND CYTOLOGICAL ANA");
INSERT INTO item_tbl VALUES("41","011 DEPARTMENT OF CLINICAL BIO-CHEMISTRY");
INSERT INTO item_tbl VALUES("42","012 URINE ANALYSIS REPORT");
INSERT INTO item_tbl VALUES("43","013 DEPARTMENT OF PATHOLOGY (COMPLETE BLOOD C");
INSERT INTO item_tbl VALUES("44","014 CULTRE REPORT FORM");
INSERT INTO item_tbl VALUES("45","AMBUBAG SILICON PEDIATRIC");
INSERT INTO item_tbl VALUES("46","015 BIRTH CERTIFICATE (SINGLE PAGE)");
INSERT INTO item_tbl VALUES("47","016 BIRTH CERTIFICATE (DOUBLE PAGE)");
INSERT INTO item_tbl VALUES("48","017 BIRTH CERTIFICATE (TELUGU)");
INSERT INTO item_tbl VALUES("49","018 LAB REQUISITION (B M P)");
INSERT INTO item_tbl VALUES("50","019 MEDICO LEGAL RECORD BOOK");
INSERT INTO item_tbl VALUES("51","020 X-RAY REPORT");
INSERT INTO item_tbl VALUES("52","2/3 GRASPERS");
INSERT INTO item_tbl VALUES("53","20 GAUGE");
INSERT INTO item_tbl VALUES("54","25A MCB 1 POLE");
INSERT INTO item_tbl VALUES("55","WIRE 26 GAUGE");
INSERT INTO item_tbl VALUES("56","3 PIN TOP 16 A");
INSERT INTO item_tbl VALUES("57","FUSE 300 A");
INSERT INTO item_tbl VALUES("58","MCB 2 POLE 32 A");
INSERT INTO item_tbl VALUES("59","6 MODILER PLATE");
INSERT INTO item_tbl VALUES("60","6 MODILER SURFACE BOX");
INSERT INTO item_tbl VALUES("61","703 SS WHITE BURS");
INSERT INTO item_tbl VALUES("62","AMP EXTRACTOR HOOK");
INSERT INTO item_tbl VALUES("63","AMP PROSTHESIS GAUZE SET OF 9");
INSERT INTO item_tbl VALUES("64","AMP RASP WITH ROD SERRATED");
INSERT INTO item_tbl VALUES("65","AO CLAMPES 2.5 MM");
INSERT INTO item_tbl VALUES("66","AO CLAMPES 3.5 MM");
INSERT INTO item_tbl VALUES("67","ABDOMINAL RETRACTO WITH DOYENS");
INSERT INTO item_tbl VALUES("68","ACGI NATS");
INSERT INTO item_tbl VALUES("69","ACGI TEX");
INSERT INTO item_tbl VALUES("70","ACID FAST STAIN KIT");
INSERT INTO item_tbl VALUES("71","ACID HARPIC");
INSERT INTO item_tbl VALUES("72","ACRYLIC TRIMING BURS");
INSERT INTO item_tbl VALUES("73","AMMONIUM SULPHATE");
INSERT INTO item_tbl VALUES("74","AMYLASE KIT");
INSERT INTO item_tbl VALUES("75","ANAESTHESIA RECORD");
INSERT INTO item_tbl VALUES("76","ANALYSER PAPER ROLL");
INSERT INTO item_tbl VALUES("77","ANAROBIC CULTURE JAR");
INSERT INTO item_tbl VALUES("78","ANESTHESIA TORLLEY - Y- COLOR (AF-78 Y-C )");
INSERT INTO item_tbl VALUES("79","ANESTHESIA TROLLEY (AF-71)");
INSERT INTO item_tbl VALUES("80","ANESTHESIA TROLLEY (AF-78)");
INSERT INTO item_tbl VALUES("81","ANESTHESIA WORKSTATION: AWS-401");
INSERT INTO item_tbl VALUES("82","ANESTHESIA WORKSTATION: AWS-402 WITH STANDARD");
INSERT INTO item_tbl VALUES("83","ANGLED GUIDE FOR COUPLING HANDLE95&135-1EACH");
INSERT INTO item_tbl VALUES("84","ANTIBIOTIC DISCS");
INSERT INTO item_tbl VALUES("85","ANTINENTAL CARD");
INSERT INTO item_tbl VALUES("86","ANTY SCALANT (WATER PLANT)");
INSERT INTO item_tbl VALUES("87","APPRON (LEAD)");
INSERT INTO item_tbl VALUES("88","APPRON NAVYBLUE");
INSERT INTO item_tbl VALUES("89","APPRON WHITE");
INSERT INTO item_tbl VALUES("90","APPRON WHITE (WITH LOGO)");
INSERT INTO item_tbl VALUES("91","APTT(TULIP)");
INSERT INTO item_tbl VALUES("92","ARALDITE");
INSERT INTO item_tbl VALUES("93","ARTERY FORCEPS 6 INCH CURVED");
INSERT INTO item_tbl VALUES("94","ARTERY FORCEPS 6 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("95","ARTERY FORCEPS 8 INCH CURVED");
INSERT INTO item_tbl VALUES("96","ARTERY FORCEPS 8 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("97","ARTHOSCOPE 30 DEGREE X 4MM STRYKER");
INSERT INTO item_tbl VALUES("98","ARTICULAATING PAPER");
INSERT INTO item_tbl VALUES("99","ASO KIT");
INSERT INTO item_tbl VALUES("100","ATTENDANCE REGISTER");
INSERT INTO item_tbl VALUES("101","ATTENDANCE REGISTER FOR THE MONTH OF");
INSERT INTO item_tbl VALUES("102","ATTENDER PASS");
INSERT INTO item_tbl VALUES("103","AUTO KERATO REFACTOMETER (KR-800)");
INSERT INTO item_tbl VALUES("104","AUTOCLAVE PORTABLE");
INSERT INTO item_tbl VALUES("105","AUTOCLAVEINDICATION TAPE IMPORTED");
INSERT INTO item_tbl VALUES("106","AUTOMATIC VOLTAGE REGULATOR SDR 1KVA(1000W)");
INSERT INTO item_tbl VALUES("107","BABCOCK 6 INCH");
INSERT INTO item_tbl VALUES("108","BABCOCK 8 INCH");
INSERT INTO item_tbl VALUES("109","BABY RESUSCITATION TROLLEY AB-43 (BABY CADALE");
INSERT INTO item_tbl VALUES("110","BABY WEIGHING SCALE");
INSERT INTO item_tbl VALUES("111","BACTERIOLOGY INCUBATOR");
INSERT INTO item_tbl VALUES("112","BALFOUR RETRACTOR");
INSERT INTO item_tbl VALUES("113","BALL BURNISHER");
INSERT INTO item_tbl VALUES("114","BALL BURNISHER BARIUM CHLORIDE");
INSERT INTO item_tbl VALUES("115","BARIUM CHLORIDE");
INSERT INTO item_tbl VALUES("116","BATTERY BIG (D)");
INSERT INTO item_tbl VALUES("117","BATTERY REMOTE (AAA)");
INSERT INTO item_tbl VALUES("118","BATTERY SMALL (C)");
INSERT INTO item_tbl VALUES("119","BATTERY WALL CLOCK (AA)");
INSERT INTO item_tbl VALUES("120","BED HEAD PANEL");
INSERT INTO item_tbl VALUES("121","BED PAN PLASTIC");
INSERT INTO item_tbl VALUES("122","BED PAN STEEL");
INSERT INTO item_tbl VALUES("123","BED SHEET CREAM COLOUR");
INSERT INTO item_tbl VALUES("124","BED SHEET PINK COLOUR");
INSERT INTO item_tbl VALUES("125","BED SHEET WHITE");
INSERT INTO item_tbl VALUES("126","BED SIDE LOCKER (ABL-56)");
INSERT INTO item_tbl VALUES("127","BED SIDE SCREEN");
INSERT INTO item_tbl VALUES("128","BENDICTS SOL");
INSERT INTO item_tbl VALUES("129","BILIRUBIN KIT");
INSERT INTO item_tbl VALUES("130","BINACULAR MICROSCOPE");
INSERT INTO item_tbl VALUES("131","BIO-DUST BIN RED");
INSERT INTO item_tbl VALUES("132","BIO-DUST BIN YELLOW");
INSERT INTO item_tbl VALUES("133","BIO-DUSTBIN COVERS RED");
INSERT INTO item_tbl VALUES("134","BIO-DUSTBIN COVERS YELLOW");
INSERT INTO item_tbl VALUES("135","BIO-HAZARD CAN");
INSERT INTO item_tbl VALUES("136","BIOCHEMISTRY ANALYSER ROLL");
INSERT INTO item_tbl VALUES("137","BIOCHEMISTRY REGISTER");
INSERT INTO item_tbl VALUES("138","BLACK CAP VIALS");
INSERT INTO item_tbl VALUES("139","BLADE (SHAVING)");
INSERT INTO item_tbl VALUES("140","BLANKET BROWN COLOUR");
INSERT INTO item_tbl VALUES("141","BLANKET CAMEL COLOUR");
INSERT INTO item_tbl VALUES("142","BLANKET GREEN COLOUR");
INSERT INTO item_tbl VALUES("143","BLANKET LITE RED COLOUR (ORANGE)");
INSERT INTO item_tbl VALUES("144","BLANKET RED COLOUR");
INSERT INTO item_tbl VALUES("145","BLEACHING POWDER");
INSERT INTO item_tbl VALUES("146","BLNT FORCEPS BIG");
INSERT INTO item_tbl VALUES("147","BLOOD BANK REFRIGERATOR BBR 300L GD (1402577)");
INSERT INTO item_tbl VALUES("148","BLOOD COLLECTION MONITOR");
INSERT INTO item_tbl VALUES("149","BLOOD COLLECTION TUBES BLACK");
INSERT INTO item_tbl VALUES("150","BLOOD COLLECTION TUBES BLACK-50,RED-50,PINK-5");
INSERT INTO item_tbl VALUES("151","BLOOD COLLECTION TUBES BLUE");
INSERT INTO item_tbl VALUES("152","BLOOD COLLECTION TUBES E D T A");
INSERT INTO item_tbl VALUES("153","BLOOD COLLECTION TUBES K2 EDTA");
INSERT INTO item_tbl VALUES("154","BLOOD COLLECTION TUBES K3 EDTA");
INSERT INTO item_tbl VALUES("155","BLOOD COLLECTION TUBES PINK");
INSERT INTO item_tbl VALUES("156","BLOOD COLLECTION TUBES PLAIN (RED CAP)");
INSERT INTO item_tbl VALUES("157","BLOOD COLLECTION TUBES PURPLE");
INSERT INTO item_tbl VALUES("158","BLOOD GROUPING KIT");
INSERT INTO item_tbl VALUES("159","BLOOD STORAGE CABINET 300 LTS");
INSERT INTO item_tbl VALUES("160","BLOOD SUGAR KIT (GLUCOSE TEST KIT)");
INSERT INTO item_tbl VALUES("161","BLOOD UREA KIT");
INSERT INTO item_tbl VALUES("162","BLOW COVERS");
INSERT INTO item_tbl VALUES("163","BLUE TIPS");
INSERT INTO item_tbl VALUES("164","BOD INCUBATOR");
INSERT INTO item_tbl VALUES("165","BOHLER STIRRUPES 8 INCH");
INSERT INTO item_tbl VALUES("166","BONDING AGENT");
INSERT INTO item_tbl VALUES("167","BONE & PLATE HOLDING FORCEPS FOR R/U MODIFIED");
INSERT INTO item_tbl VALUES("168","BONE AWL FOR HUMERUS SMALL");
INSERT INTO item_tbl VALUES("169","BONE AWL FOR R/U TAPPERED");
INSERT INTO item_tbl VALUES("170","BONE CUTTER 5/A");
INSERT INTO item_tbl VALUES("171","BONE CUTTING FORECEPS SINGLE ACTION ST 7 1/2");
INSERT INTO item_tbl VALUES("172","BONE DRILL UNIVERSAL");
INSERT INTO item_tbl VALUES("173","BONE FILE");
INSERT INTO item_tbl VALUES("174","BONE GRAFT PUNCH STRAIGHT");
INSERT INTO item_tbl VALUES("175","BONE HOLDING FORCEPS -POINTED 5,6 INCH");
INSERT INTO item_tbl VALUES("176","BONE HOOKES 10 INCH");
INSERT INTO item_tbl VALUES("177","BONE LEAVER FOR HUMERES / TIBIA SERRATED");
INSERT INTO item_tbl VALUES("178","BONE LEAVER FOR HUMERS/ TIBIA PLAIN");
INSERT INTO item_tbl VALUES("179","BONE LEAVERS FOR RADIUS");
INSERT INTO item_tbl VALUES("180","BONE LEAVERS FOR SERRATED");
INSERT INTO item_tbl VALUES("181","BONE LEAVERS FOR TRETHWON");
INSERT INTO item_tbl VALUES("182","BONE NEBBLER 7.5");
INSERT INTO item_tbl VALUES("183","BONE NIBBLER (D.A) BIG");
INSERT INTO item_tbl VALUES("184","BONE NIBBLER DOUBLE AC");
INSERT INTO item_tbl VALUES("185","BONE NIBBLERS SINGLE ACTION ST 5 1/2 INCH");
INSERT INTO item_tbl VALUES("186","BONE NIBULAR (SARGENT RONGEUR): BIG");
INSERT INTO item_tbl VALUES("187","BONE SCOOP (VOLKMAN) DOUBLE ENDED MEDIUM");
INSERT INTO item_tbl VALUES("188","BONE SCOOP (VOLKMAN) DOUBLE ENDED SET OF 3");
INSERT INTO item_tbl VALUES("189","BONE SCOOP WITH FIBRE HANDLE LONG");
INSERT INTO item_tbl VALUES("190","BOSCH DRILL MECHIENE");
INSERT INTO item_tbl VALUES("191","BOUGIE PAEDIATRIC");
INSERT INTO item_tbl VALUES("192","BOULS BIG STEEL");
INSERT INTO item_tbl VALUES("193","BOULS SMALL STEEL");
INSERT INTO item_tbl VALUES("194","BOWLED HOLDING GRASPER");
INSERT INTO item_tbl VALUES("195","BOX FILE BIG");
INSERT INTO item_tbl VALUES("196","BOX FILE SMALL");
INSERT INTO item_tbl VALUES("197","BP APPARATUS");
INSERT INTO item_tbl VALUES("198","BP APPARATUS BULB");
INSERT INTO item_tbl VALUES("199","BP APPARATUS DIGITAL");
INSERT INTO item_tbl VALUES("200","BP APPARATUS HAND CUF");
INSERT INTO item_tbl VALUES("201","BP APPARATUS: STAND MODEL");
INSERT INTO item_tbl VALUES("202","BP BLADE NO:15");
INSERT INTO item_tbl VALUES("203","BP CUFF WITH BAG");
INSERT INTO item_tbl VALUES("204","BP HANDLE NO 3");
INSERT INTO item_tbl VALUES("205","BP HANDLE NO 4");
INSERT INTO item_tbl VALUES("206","BP HANDLE NO 7");
INSERT INTO item_tbl VALUES("207","BPC FLOWMETER WITH CONNECTING INLET (CENTRAL)");
INSERT INTO item_tbl VALUES("208","BRISTOW PERISTEAL ELEVATOR");
INSERT INTO item_tbl VALUES("209","BROACHERS");
INSERT INTO item_tbl VALUES("210","BROKEN SCREW REMOVEL FORCEPS: 3.5MM");
INSERT INTO item_tbl VALUES("211","BROKEN SCREW REMOVEL FORCEPS: 4.5MM");
INSERT INTO item_tbl VALUES("212","BROOMSTICK COCONUT");
INSERT INTO item_tbl VALUES("213","BROOMSTICK KUNCH");
INSERT INTO item_tbl VALUES("214","BRUSH SHINK CLEANING");
INSERT INTO item_tbl VALUES("215","BRUSH WASHING");
INSERT INTO item_tbl VALUES("216","BRUSH WC & IC");
INSERT INTO item_tbl VALUES("217","BULB 12V 50W");
INSERT INTO item_tbl VALUES("218","BUNSEN BERNER");
INSERT INTO item_tbl VALUES("219","BURS");
INSERT INTO item_tbl VALUES("220","BUVI");
INSERT INTO item_tbl VALUES("221","BW BIX");
INSERT INTO item_tbl VALUES("222","C- ARM COVERS (1+1)");
INSERT INTO item_tbl VALUES("223","C-ARM MACHINE SET");
INSERT INTO item_tbl VALUES("224","C.C BOLT : 85 6.0MM");
INSERT INTO item_tbl VALUES("225","CALCIUM CHLORIDE TULIP");
INSERT INTO item_tbl VALUES("226","CALCIUM HYDROXIDE POWDER");
INSERT INTO item_tbl VALUES("227","CALCIUM KIT");
INSERT INTO item_tbl VALUES("228","CALCULATOR");
INSERT INTO item_tbl VALUES("229","CALLING BELL");
INSERT INTO item_tbl VALUES("230","CAMERA CONSOLE HD 1188 STRYKER");
INSERT INTO item_tbl VALUES("231","CAMERA HEAD CUPPLING 1188 STRYKER");
INSERT INTO item_tbl VALUES("232","CANNULATED SCREW DRIVERS");
INSERT INTO item_tbl VALUES("233","CANULATED DRILL HAND PIECE SET");
INSERT INTO item_tbl VALUES("234","CAPACITOR (CONDUNCER)");
INSERT INTO item_tbl VALUES("235","CAPELLARY TUBES");
INSERT INTO item_tbl VALUES("236","CARBON PAPER (100 NOS PKT)");
INSERT INTO item_tbl VALUES("237","CASSETTE SPLIT A/C 1.5 TON");
INSERT INTO item_tbl VALUES("238","CASSETTE SPLIT A/C 2 TON");
INSERT INTO item_tbl VALUES("239","CASSETTE SPLIT A/C 3 TON");
INSERT INTO item_tbl VALUES("240","CASUALTY REGISTER");
INSERT INTO item_tbl VALUES("241","CATRIDGE HP LASERJET 1020 PLUS");
INSERT INTO item_tbl VALUES("242","CATRIDGE LASERJET P1008");
INSERT INTO item_tbl VALUES("243","CATS PAW RETRACTOR");
INSERT INTO item_tbl VALUES("244","CC DRILL BIT FOR 4 MM");
INSERT INTO item_tbl VALUES("245","CC DRILL BIT FOR 6.5 MM");
INSERT INTO item_tbl VALUES("246","CC SCREW DRIVER FOR 4MM");
INSERT INTO item_tbl VALUES("247","CC SCREW DRIVER FOR 6.4MM");
INSERT INTO item_tbl VALUES("248","CC TAP FOR 4MM");
INSERT INTO item_tbl VALUES("249","CC TAP FOR 6.5MM");
INSERT INTO item_tbl VALUES("250","CD WITH COVER");
INSERT INTO item_tbl VALUES("251","CELL CONTROLERS PAK");
INSERT INTO item_tbl VALUES("252","CEMENT MIXING SPATULA");
INSERT INTO item_tbl VALUES("253","CENTRIFUGE MODEL-C854/6");
INSERT INTO item_tbl VALUES("254","CENTRING SLEEVE FOR TAP");
INSERT INTO item_tbl VALUES("255","CENTRING SLEEVES FOR WRENCH (SPANNER)");
INSERT INTO item_tbl VALUES("256","CHANLY RETRACTOR WAIT WITH CHAIN");
INSERT INTO item_tbl VALUES("257","CHARRGING ADAPTOR (BP APPARATUS)");
INSERT INTO item_tbl VALUES("258","CHEEK RETRACTOR");
INSERT INTO item_tbl VALUES("259","CHEETAL FORCEPS");
INSERT INTO item_tbl VALUES("260","CHISEL STILL TYPE OSTEOTOME 5MM & 10MM");
INSERT INTO item_tbl VALUES("261","CHLORESTEROL");
INSERT INTO item_tbl VALUES("262","CHOLESTROL KIT");
INSERT INTO item_tbl VALUES("263","CHOWK 4X14");
INSERT INTO item_tbl VALUES("264","CIG NOX");
INSERT INTO item_tbl VALUES("265","CILP PAD (EXAMINATION PAD)");
INSERT INTO item_tbl VALUES("266","CLINICAL CENTRIFUGE WITH SWING HEAD");
INSERT INTO item_tbl VALUES("267","CLIP APPLICATOR 10MM 2:1");
INSERT INTO item_tbl VALUES("268","CLIP APPLICATOR 10MM 3:1");
INSERT INTO item_tbl VALUES("269","CLOTH");
INSERT INTO item_tbl VALUES("270","CO2 SINGLE STAGE REGULATOR");
INSERT INTO item_tbl VALUES("271","CO2 TUBING TYPE SPECIAL 5 THERED KIT AMERICAN");
INSERT INTO item_tbl VALUES("272","COBB S SPINAL ELEVATOR: 10");
INSERT INTO item_tbl VALUES("273","COBB S SPINAL ELEVATOR: 15");
INSERT INTO item_tbl VALUES("274","COBBS SPINAL ELIVATOR");
INSERT INTO item_tbl VALUES("275","COLIN");
INSERT INTO item_tbl VALUES("276","COMPAMEDIC AIR COMPRESSOR");
INSERT INTO item_tbl VALUES("277","COMPO SAFE WEIGHING SCALE (1312474)");
INSERT INTO item_tbl VALUES("278","COMPOSCALE");
INSERT INTO item_tbl VALUES("279","COMPOSIT KIT (IVOCALER)");
INSERT INTO item_tbl VALUES("280","COMPOSITER");
INSERT INTO item_tbl VALUES("281","COMPRESSION /DISSTRACTION ROD 8 INCH");
INSERT INTO item_tbl VALUES("282","COMPRESSOR");
INSERT INTO item_tbl VALUES("283","COMPRESSSION /DISSTRACTION ROD 6 INCH");
INSERT INTO item_tbl VALUES("284","COMPUTER TABLE (1500Lx1500Wx750H)");
INSERT INTO item_tbl VALUES("285","COMPUTER TABLE (2200LX600WX750H)");
INSERT INTO item_tbl VALUES("286","COMPUTERISED TONOMETER (CT-80)");
INSERT INTO item_tbl VALUES("287","CONDENSOR");
INSERT INTO item_tbl VALUES("288","CONDOMS");
INSERT INTO item_tbl VALUES("289","CONNECTING CABLE FOR FLOW SENSOR FOR DRAEGER");
INSERT INTO item_tbl VALUES("290","CONNECTING NUTES");
INSERT INTO item_tbl VALUES("291","CONNECTION BOLTES");
INSERT INTO item_tbl VALUES("292","CONNECTOR OF ANESTHESIA MACHINE");
INSERT INTO item_tbl VALUES("293","CONSENT FOR COUNSELING FORM");
INSERT INTO item_tbl VALUES("294","CONSENT FORM");
INSERT INTO item_tbl VALUES("295","COPILING JAR");
INSERT INTO item_tbl VALUES("296","CORBANDYOXIDE CYLENDER (CO2 CYLENDER)");
INSERT INTO item_tbl VALUES("297","COT FOWLER CASUALTY (AB-21)");
INSERT INTO item_tbl VALUES("298","COT ICU BED- FIVE FUNCTION (ELECTRO) (AMB-2)");
INSERT INTO item_tbl VALUES("299","COT PAEDIATRICS");
INSERT INTO item_tbl VALUES("300","COT SEMI COT FOWLER (GENERAL) (AB-35)");
INSERT INTO item_tbl VALUES("301","COTTON ROLL");
INSERT INTO item_tbl VALUES("302","COUCHER STRAIGHT 8 INCH");
INSERT INTO item_tbl VALUES("303","COUNTER SINK 8.0MM HEAD FOR 4.5/6.5MM");
INSERT INTO item_tbl VALUES("304","COUNTER SINK FOR 3.5MM & SCREWS");
INSERT INTO item_tbl VALUES("305","COUNTER SINK FOR 3.5MM & SCREWS");
INSERT INTO item_tbl VALUES("306","COVER SLIPS DIFFERENT SIZES");
INSERT INTO item_tbl VALUES("307","CRASH CART EMERGENCY(AF-91)");
INSERT INTO item_tbl VALUES("308","CREATININE KIT S R");
INSERT INTO item_tbl VALUES("309","CRP KIT");
INSERT INTO item_tbl VALUES("310","CRYO BATH 1403300");
INSERT INTO item_tbl VALUES("311","CRYO MACHINE");
INSERT INTO item_tbl VALUES("312","CSF DILUTING FLUID");
INSERT INTO item_tbl VALUES("313","CT SCAN FILM COVERS");
INSERT INTO item_tbl VALUES("314","CT SCANER GE HISPEED NXI DUAL SLICE WITH STAN");
INSERT INTO item_tbl VALUES("315","CT SCAN FILM COVERS");
INSERT INTO item_tbl VALUES("316","CTG PAPER ROLL (BT-350)");
INSERT INTO item_tbl VALUES("317","CUFF FOR CHILD");
INSERT INTO item_tbl VALUES("318","CUFF FOR LONG ARM");
INSERT INTO item_tbl VALUES("319","CUFF FOR LONG ARM CUFF FOR LONG LEG");
INSERT INTO item_tbl VALUES("320","CUFF FOR STANDARD ARM");
INSERT INTO item_tbl VALUES("321","CUFF FOR STANDARD FOR LEG");
INSERT INTO item_tbl VALUES("322","CUP BOARD 4 RACKS GLASS");
INSERT INTO item_tbl VALUES("323","CURRET DIFFENT (SIZE)");
INSERT INTO item_tbl VALUES("324","CUSCO SPECULAM LARGE");
INSERT INTO item_tbl VALUES("325","CUSCO SPECULAM MEDIUM");
INSERT INTO item_tbl VALUES("326","CUSCO SPECULAM SMALL");
INSERT INTO item_tbl VALUES("327","CYCLO MIXTURE");
INSERT INTO item_tbl VALUES("328","CYLENDAR TROLLE (SS)");
INSERT INTO item_tbl VALUES("329","CYLENDAR TROLLEY (EPC)");
INSERT INTO item_tbl VALUES("330","CZERNY RECTRACTOR 6 INCH");
INSERT INTO item_tbl VALUES("331","CZERNY RECTRACTOR 8 INCH");
INSERT INTO item_tbl VALUES("332","DHS TRIPAL REMAR");
INSERT INTO item_tbl VALUES("333","DAP & DIPS");
INSERT INTO item_tbl VALUES("334","DEAPTH GAUZE WITH LASER SCALE (3.5MM)");
INSERT INTO item_tbl VALUES("335","DEAPTH GAUZE WITH LASER SCALE (4.5MM)");
INSERT INTO item_tbl VALUES("336","DEDICATED SOILED LINEN TROLLEY (AF-84)");
INSERT INTO item_tbl VALUES("337","DEEP FREEZER-40 LOT NO- 1403356");
INSERT INTO item_tbl VALUES("338","DEEP FREEZER-80 LOT NO- 1403257");
INSERT INTO item_tbl VALUES("339","DEFIBRILLATOR WITH PACER WITH PADDLE HP CODE");
INSERT INTO item_tbl VALUES("340","DENGUE");
INSERT INTO item_tbl VALUES("341","DENTAL CHAIR SET ( ACCESSERIES)");
INSERT INTO item_tbl VALUES("342","DENTYPLY ZINC PHOSPHATE");
INSERT INTO item_tbl VALUES("343","DEPTH GAUGE (LONG WITH LASER SCALE):4.5MM");
INSERT INTO item_tbl VALUES("344","DEPTH GAUGE (WITH LASER SCALE): 3.5MM");
INSERT INTO item_tbl VALUES("345","DHS TAP WITH COUPLING END");
INSERT INTO item_tbl VALUES("346","DHS WRENCH/EXTRACTOR WITH COUPLING SCREW-LONG");
INSERT INTO item_tbl VALUES("347","DI ETHYL ETHER");
INSERT INTO item_tbl VALUES("348","DIANAMOMETRIC TENSIONER");
INSERT INTO item_tbl VALUES("349","DIASTONE");
INSERT INTO item_tbl VALUES("350","DIATRO CLEANER");
INSERT INTO item_tbl VALUES("351","DIATROLYSE DIFF");
INSERT INTO item_tbl VALUES("352","DICALS");
INSERT INTO item_tbl VALUES("353","DIESTONE PKT");
INSERT INTO item_tbl VALUES("354","DIG CALORIMETER");
INSERT INTO item_tbl VALUES("355","DIGITAL BALANCE 0.01G");
INSERT INTO item_tbl VALUES("356","DIGITAL FLAME PHOTOMETER");
INSERT INTO item_tbl VALUES("357","DILIENT FOR HEMATOLOGY ANALYSERS-20LTRS");
INSERT INTO item_tbl VALUES("358","DIRECT MEASURING DEVICE");
INSERT INTO item_tbl VALUES("359","DISK PUNCH DOWNWARD,2 MM");
INSERT INTO item_tbl VALUES("360","DISK PUNCH DOWNWARD,3 MM");
INSERT INTO item_tbl VALUES("361","DISK PUNCH DOWNWARD,4 MM");
INSERT INTO item_tbl VALUES("362","DISK PUNCH DOWNWARD,5 MM");
INSERT INTO item_tbl VALUES("363","DISK PUNCH STRAIGHT,2 MM");
INSERT INTO item_tbl VALUES("364","DISK PUNCH STRAIGHT,3 MM");
INSERT INTO item_tbl VALUES("365","DISK PUNCH STRAIGHT,4 MM");
INSERT INTO item_tbl VALUES("366","DISK PUNCH STRAIGHT,5 MM");
INSERT INTO item_tbl VALUES("367","DISK PUNCH UPWARD,2 MM");
INSERT INTO item_tbl VALUES("368","DISK PUNCH UPWARD,2 MM");
INSERT INTO item_tbl VALUES("369","DISK PUNCH UPWARD,4 MM");
INSERT INTO item_tbl VALUES("370","DISK PUNCH UPWARD,5 MM");
INSERT INTO item_tbl VALUES("371","DISPLAY BOARD 36X20 INCH");
INSERT INTO item_tbl VALUES("372","DISPODENT DROPS");
INSERT INTO item_tbl VALUES("373","DISSECTER PROBE DOUBLE ENDED");
INSERT INTO item_tbl VALUES("374","DISSECTING FORCEPS 6 INCH");
INSERT INTO item_tbl VALUES("375","DISSECTING FORCEPS 6 INCH TOOTHED");
INSERT INTO item_tbl VALUES("376","DISSECTING FORCEPS 8 INCH");
INSERT INTO item_tbl VALUES("377","DISSECTING FORCEPS 8 INCH NON TOOTHED");
INSERT INTO item_tbl VALUES("378","DISSECTING FORCEPS 8 INCH TOOTHED");
INSERT INTO item_tbl VALUES("379","DISTLE WATER");
INSERT INTO item_tbl VALUES("380","DIVIRS RETRACTOR 2.5");
INSERT INTO item_tbl VALUES("381","DOCTORS OPERATIVE STOOL");
INSERT INTO item_tbl VALUES("382","DONOR COUCH 1403004");
INSERT INTO item_tbl VALUES("383","DOUBLE CLAMPES 4.5 MM");
INSERT INTO item_tbl VALUES("384","DOYENS RETRACTOR 2 INCH");
INSERT INTO item_tbl VALUES("385","DOYENS RETRACTOR 2.5 INCH");
INSERT INTO item_tbl VALUES("386","DOYENS RETRACTOR 3 INCH");
INSERT INTO item_tbl VALUES("387","DR GOWNS");
INSERT INTO item_tbl VALUES("388","DRABKINN SOLUTION");
INSERT INTO item_tbl VALUES("389","DRESSING BIN 9X11 INCH");
INSERT INTO item_tbl VALUES("390","DRESSING BIN ROUND 12X15 INCH");
INSERT INTO item_tbl VALUES("391","DRESSING BIN ROUND 9X12 INCH");
INSERT INTO item_tbl VALUES("392","DRESSING REGISTER");
INSERT INTO item_tbl VALUES("393","DRESSING TROLLEY (AF-87)");
INSERT INTO item_tbl VALUES("394","DRESSING TROLLEY - Y -SS (AF-87 Y- SS)");
INSERT INTO item_tbl VALUES("395","DRESSING TROLLEY-Y- COLOR (AF-87 Y-C)");
INSERT INTO item_tbl VALUES("396","DRII/SCREW/WIRE GAUGE SCALE 6 INCH");
INSERT INTO item_tbl VALUES("397","DRILL & TAP SLEEVE BOUBLE ENDED 4.5");
INSERT INTO item_tbl VALUES("398","DRILL & TAP SLEEVE DOUBLE ENDED: 3.5MM");
INSERT INTO item_tbl VALUES("399","DRILL BIT 2.5");
INSERT INTO item_tbl VALUES("400","DRILL BIT 2.7");
INSERT INTO item_tbl VALUES("401","DRILL BIT : 3.2MM");
INSERT INTO item_tbl VALUES("402","DRILL BITES H SS 8 INCH 2.5");
INSERT INTO item_tbl VALUES("403","DRILL BITES H SS 8 INCH 2.7");
INSERT INTO item_tbl VALUES("404","DRILL BITES H SS 8 INCH 3.2");
INSERT INTO item_tbl VALUES("405","DRILL BITES H SS 8 INCH 3.5");
INSERT INTO item_tbl VALUES("406","DRILL BITES H SS 8 INCH 4.0");
INSERT INTO item_tbl VALUES("407","DRILL BITES S.S WITH COUPLING END 2.7");
INSERT INTO item_tbl VALUES("408","DRILL BITES S.S WITH COUPLING END 3.2");
INSERT INTO item_tbl VALUES("409","DRILL BITES: 2.8MM");
INSERT INTO item_tbl VALUES("410","DRILL BITES: 3.5MM");
INSERT INTO item_tbl VALUES("411","DRILL BITES: 4.5MM 6 INCH");
INSERT INTO item_tbl VALUES("412","DRILL BITES: 4.5MM 9 INCH");
INSERT INTO item_tbl VALUES("413","DRILL SLEEVE FOR DCP CENTRIC & ECCENTRIC 3.5M");
INSERT INTO item_tbl VALUES("414","DRILL SLEEVE FOR DCP CENTRIC & ECCENTRIC 4.5M");
INSERT INTO item_tbl VALUES("415","DRILL SLEEVE FOR LOCKING PLATE 2.2");
INSERT INTO item_tbl VALUES("416","DRILL SLEEVE FOR LOCKING PLATE 3.2");
INSERT INTO item_tbl VALUES("417","DRILL SLEEVE FOR LOCKING PLATE 4");
INSERT INTO item_tbl VALUES("418","DRILL SLEEVE FOR LOCKING PLATE 4.5");
INSERT INTO item_tbl VALUES("419","DRILL SLEEVE- 2.7MM");
INSERT INTO item_tbl VALUES("420","DRILL SLEEVE- 3.2MM");
INSERT INTO item_tbl VALUES("421","DRILL TAP 3.5MM 14 TPI");
INSERT INTO item_tbl VALUES("422","DRILL TAP 3.5MM 20 TPI");
INSERT INTO item_tbl VALUES("423","DRILL TAP 4.5MM");
INSERT INTO item_tbl VALUES("424","DRILL TAP 6.5MM C.C TAP");
INSERT INTO item_tbl VALUES("425","DRILL TAP SLEEVE 2.7/3.5MM");
INSERT INTO item_tbl VALUES("426","DRILL TAP SLEEVE 3.2/4.5MM");
INSERT INTO item_tbl VALUES("427","DRILL TAP: 3.5MM");
INSERT INTO item_tbl VALUES("428","DRIVING UNIT WITH ALL ITEMS SET");
INSERT INTO item_tbl VALUES("429","DURA RETRACTOR");
INSERT INTO item_tbl VALUES("430","DUST BIN COVERS SMALL");
INSERT INTO item_tbl VALUES("431","DUST PAN");
INSERT INTO item_tbl VALUES("432","DUST BIN SMALL");
INSERT INTO item_tbl VALUES("433","DUSTING CLOTH (CLEANING)");
INSERT INTO item_tbl VALUES("434","DVD WITH COVER");
INSERT INTO item_tbl VALUES("435","DVI CABLE");
INSERT INTO item_tbl VALUES("436","DYCAL");
INSERT INTO item_tbl VALUES("437","DYONICS FOOT SWITCH");
INSERT INTO item_tbl VALUES("438","E T TUBE STILLEST");
INSERT INTO item_tbl VALUES("439","ECG 3 LEAD CABLE HP/PHILIPS");
INSERT INTO item_tbl VALUES("440","ECG ADULT PERIPHERAL CALMP ELECTRODES");
INSERT INTO item_tbl VALUES("441","ECG BATTERY 18V 4000MAH NIMH (FOR MAC 5000)");
INSERT INTO item_tbl VALUES("442","ECG CABLE 10 LEAD");
INSERT INTO item_tbl VALUES("443","ECG CAM 14 ACCQUISITION MODULE");
INSERT INTO item_tbl VALUES("444","ECG INTERPRETATION");
INSERT INTO item_tbl VALUES("445","ECG MACHINE (6 CHANNEL WITH INTERPRETION)");
INSERT INTO item_tbl VALUES("446","ECG MACHINE MAC-5000 GE MAQUETTE");
INSERT INTO item_tbl VALUES("447","ECG PAPER ROLL GE (MAC-5000)");
INSERT INTO item_tbl VALUES("448","ECG REGISTER");
INSERT INTO item_tbl VALUES("449","ECG SUCTION CHEST ELECTRODES");
INSERT INTO item_tbl VALUES("450","ELECTRICAL INSULATION TAPE");
INSERT INTO item_tbl VALUES("451","ELECTROLYTE ANALYSER GEL PACK");
INSERT INTO item_tbl VALUES("452","ELECTROLYTE ANALYSER ROLL");
INSERT INTO item_tbl VALUES("453","ELISA READER ASPEN");
INSERT INTO item_tbl VALUES("454","ELISA READER ASPENv");
INSERT INTO item_tbl VALUES("455","ELISA WASHER ASPEN");
INSERT INTO item_tbl VALUES("456","ELLEN KEYS SET (SET OF 10 NOS)");
INSERT INTO item_tbl VALUES("457","EMERGENCY STRETCHER: MANUAL (AF-66)");
INSERT INTO item_tbl VALUES("458","EMERGENCY TROLLEY (AF-76)");
INSERT INTO item_tbl VALUES("459","ENDO BOX");
INSERT INTO item_tbl VALUES("460","ENDOMETRIAL CURETLE SMALL");
INSERT INTO item_tbl VALUES("461","ENEMA CAN WITH TUBES");
INSERT INTO item_tbl VALUES("462","ENVOLOPE COVERS 10X4");
INSERT INTO item_tbl VALUES("463","EOSIN YELLOW");
INSERT INTO item_tbl VALUES("464","EPICIOTOMY SCISSOR");
INSERT INTO item_tbl VALUES("465","ERASER");
INSERT INTO item_tbl VALUES("466","ESR COLLECTION TUBES (BLACK CAP)");
INSERT INTO item_tbl VALUES("467","ESR PIPPETS");
INSERT INTO item_tbl VALUES("468","ET CHANT");
INSERT INTO item_tbl VALUES("469","EUGENOL PASTE");
INSERT INTO item_tbl VALUES("470","EXAMINATION TABLE CLOTH");
INSERT INTO item_tbl VALUES("471","EXAMINATION TABLE-EPC (AB-47)");
INSERT INTO item_tbl VALUES("472","EXAMINATION TABLE-GYNAE (AB-52)");
INSERT INTO item_tbl VALUES("473","EXTENSION POST MALE FEMALE: 1,2,3,4,5,6");
INSERT INTO item_tbl VALUES("474","EXTERNAL FIXATOR UNIVER SEL CLAMPES 4.5 MM");
INSERT INTO item_tbl VALUES("475","EXTERNAL FIXATOR/ DISSTRACTOR FOR FINGER SING");
INSERT INTO item_tbl VALUES("476","FACE MASK");
INSERT INTO item_tbl VALUES("477","FAREBEUF CURVED");
INSERT INTO item_tbl VALUES("478","FAREBEUF STRAIGHT");
INSERT INTO item_tbl VALUES("479","FEMOUREL STEP REAMER BIG");
INSERT INTO item_tbl VALUES("480","FEMOUREL STEP REAMER SMALL");
INSERT INTO item_tbl VALUES("481","FETAL DOPPLER (HI-BEBE)");
INSERT INTO item_tbl VALUES("482","FETAL MONITOR(CTG): TWIN (BT 350)");
INSERT INTO item_tbl VALUES("483","FEVIQUICK");
INSERT INTO item_tbl VALUES("484","GUM STICK (GLUSTICK)");
INSERT INTO item_tbl VALUES("485","FIBRE OPTIC CABLE");
INSERT INTO item_tbl VALUES("486","FILE URGENT/ORDINERY");
INSERT INTO item_tbl VALUES("487","FILES SET");
INSERT INTO item_tbl VALUES("488","FILTER PAPER CIRCLES");
INSERT INTO item_tbl VALUES("489","FIRE BUCKETS (4X1)");
INSERT INTO item_tbl VALUES("490","FIRE EXTINGUISHERS ABC TYPE 6 KG");
INSERT INTO item_tbl VALUES("491","FIRE EXTINGUISHERS ABC TYPE 6 KG FIRE EXTINGUISHERS CO2 TYPE 4.5 KG");
INSERT INTO item_tbl VALUES("492","FIXATOR R/U COLLE S O SWIEL CLAMPES DISTRACT");
INSERT INTO item_tbl VALUES("493","FLANK WRTING PAD");
INSERT INTO item_tbl VALUES("494","FLASK GLASS");
INSERT INTO item_tbl VALUES("495","FLAT PANEL MONITOR SV2 STRYKER");
INSERT INTO item_tbl VALUES("496","FLEXIBLE REAMER SHAFT FOR DETACHABLE HEADS");
INSERT INTO item_tbl VALUES("497","FLEXIBLE SHAFT FOR DRIVE UNIT");
INSERT INTO item_tbl VALUES("498","FLOW SENSOR: AWS 402");
INSERT INTO item_tbl VALUES("499","FOAM BOARDS WITH STICKER");
INSERT INTO item_tbl VALUES("500","FOETOSCOPE (ALUMINIUM)");
INSERT INTO item_tbl VALUES("501","FOOT STEP DOUBLE (AF-96)");
INSERT INTO item_tbl VALUES("502","FOOT STEP SINGLE (AF-95)");
INSERT INTO item_tbl VALUES("503","FORCEPS STEEL");
INSERT INTO item_tbl VALUES("504","FORMACRASOL");
INSERT INTO item_tbl VALUES("505","FORMALDEHYDE");
INSERT INTO item_tbl VALUES("506","FOUCHET REGENT");
INSERT INTO item_tbl VALUES("507","FOXPLANE");
INSERT INTO item_tbl VALUES("508","FOXPLANE FUME HOOD (1500Lx750Wx2400H)");
INSERT INTO item_tbl VALUES("509","FUMIGATOR");
INSERT INTO item_tbl VALUES("510","GALL BLADDER EXTN.10 MM");
INSERT INTO item_tbl VALUES("511","GC 9 BIG");
INSERT INTO item_tbl VALUES("512","GC I BIG");
INSERT INTO item_tbl VALUES("513","GC II MINI");
INSERT INTO item_tbl VALUES("514","GDC CROWN REMOVER");
INSERT INTO item_tbl VALUES("515","GDC CURRETERS");
INSERT INTO item_tbl VALUES("516","GDC ELEVATORS");
INSERT INTO item_tbl VALUES("517","GDC FILLING INSTRUMENTS");
INSERT INTO item_tbl VALUES("518","GDC FORCEPS");
INSERT INTO item_tbl VALUES("519","GDC MOUTH MIRROR SETS (DIOGANSTIC KIT)");
INSERT INTO item_tbl VALUES("520","GDC SURGICAL KIT");
INSERT INTO item_tbl VALUES("521","GEL PENS");
INSERT INTO item_tbl VALUES("522","GIC FUJI-1");
INSERT INTO item_tbl VALUES("523","GIC FUJI-9");
INSERT INTO item_tbl VALUES("524","GIGILISA WIRE");
INSERT INTO item_tbl VALUES("525","GIGLE SAW WIRES");
INSERT INTO item_tbl VALUES("526","GLASS DISPOSIBLE");
INSERT INTO item_tbl VALUES("527","GLASS SLAB");
INSERT INTO item_tbl VALUES("528","GLOUCOSE KIT(BLOOD SUGAR KIT)");
INSERT INTO item_tbl VALUES("529","GLOUSES SMALL BOX");
INSERT INTO item_tbl VALUES("530","GLUCOMETER WITH STRIPS");
INSERT INTO item_tbl VALUES("531","GLYCEROL (500ML)");
INSERT INTO item_tbl VALUES("532","GOOD NIGHT LAMP (EDGE GLOW)");
INSERT INTO item_tbl VALUES("533","GOUGE STILL TYPE, OSTEOTOME 5MM");
INSERT INTO item_tbl VALUES("534","GP POINTS");
INSERT INTO item_tbl VALUES("535","GRAMS STAIN KIT");
INSERT INTO item_tbl VALUES("536","GREEN CLOTH");
INSERT INTO item_tbl VALUES("537","GREEN STICKS BOX");
INSERT INTO item_tbl VALUES("538","GREEN STONE");
INSERT INTO item_tbl VALUES("539","GROUND MOUNTED CUPBOARD (600L X 375W X 2100H)");
INSERT INTO item_tbl VALUES("540","GUIDE WIRE THREDED 1.2MMX9 INCH");
INSERT INTO item_tbl VALUES("541","GUIDE WIRE THREDED 1.8MMX9 INCH");
INSERT INTO item_tbl VALUES("542","GUIDE WIRES 2.5MM");
INSERT INTO item_tbl VALUES("543","GUM BOTTLE");
INSERT INTO item_tbl VALUES("544","HR REGISTER (HUMAN RESOURCE REGISTER)");
INSERT INTO item_tbl VALUES("545","H-PROBE");
INSERT INTO item_tbl VALUES("546","HALF RINGES: 140");
INSERT INTO item_tbl VALUES("547","HALF RINGES: 160");
INSERT INTO item_tbl VALUES("548","HALF RINGES: 180");
INSERT INTO item_tbl VALUES("549","HALOTHANE BOTTLE");
INSERT INTO item_tbl VALUES("550","HAMMER-SS HANDLE MEDIUM");
INSERT INTO item_tbl VALUES("551","HAMMER-SS HANDLE SMALL");
INSERT INTO item_tbl VALUES("552","HAMMER: SMALL");
INSERT INTO item_tbl VALUES("553","HAND GLOVES 15 KV");
INSERT INTO item_tbl VALUES("554","HAND GLOVES 30 KV");
INSERT INTO item_tbl VALUES("555","HANDLE WITH SS CHUCK & KEY");
INSERT INTO item_tbl VALUES("556","HANDWASH LIQUID");
INSERT INTO item_tbl VALUES("557","HANDWASH REFILL");
INSERT INTO item_tbl VALUES("558","HARPIC");
INSERT INTO item_tbl VALUES("559","HBSAG KIT");
INSERT INTO item_tbl VALUES("560","HCL N/10");
INSERT INTO item_tbl VALUES("561","HCV KIT");
INSERT INTO item_tbl VALUES("562","HEAD EXTRACTOR JUDET");
INSERT INTO item_tbl VALUES("563","HEAMOMETER");
INSERT INTO item_tbl VALUES("564","HEAMOTOLOGY ANALYSER");
INSERT INTO item_tbl VALUES("565","HEAMOTOLOGY ANALYSER (3 PART DIFFERENTIAL)DIA");
INSERT INTO item_tbl VALUES("566","HEAMOTOLOGY ANALYSER CELL PACK & CLEANER");
INSERT INTO item_tbl VALUES("567","HEAMOTOLOGY ANALYSER CLEANER");
INSERT INTO item_tbl VALUES("568","HEAMOTOLOGY ANALYSER FILLING PACK");
INSERT INTO item_tbl VALUES("569","HEAMOTOLOGY ANALYSER GEL PACK");
INSERT INTO item_tbl VALUES("570","HEAMOTOLOGY ANALYSER LYES AND CLEENER");
INSERT INTO item_tbl VALUES("571","HIT");
INSERT INTO item_tbl VALUES("572","HEATING ELEMENT (HOTWATER STERLIZER)");
INSERT INTO item_tbl VALUES("573","HEGARS DILATORS (SET OF 8 NOS)");
INSERT INTO item_tbl VALUES("574","HEIGHT SCALE (STATURE METER)");
INSERT INTO item_tbl VALUES("575","HEMOCYTOMETER");
INSERT INTO item_tbl VALUES("576","HEMOGLOBULIN SOLUTION");
INSERT INTO item_tbl VALUES("577","HEMOMETER");
INSERT INTO item_tbl VALUES("578","HEMOTOXYLENE SOLUTION");
INSERT INTO item_tbl VALUES("579","HEY GROVES BONE HOLDING FORCEPS WITH SPEED LO");
INSERT INTO item_tbl VALUES("580","PENS HI-LIGHT ");
INSERT INTO item_tbl VALUES("581","HINGES MALE FEMALE: 1");
INSERT INTO item_tbl VALUES("582","HIV KIT");
INSERT INTO item_tbl VALUES("583","HOHMAN RETRACTIRES 10MM");
INSERT INTO item_tbl VALUES("584","HOHMAN RETRACTOR 30MM");
INSERT INTO item_tbl VALUES("585","HOHMAN RETRACTORES 20MM");
INSERT INTO item_tbl VALUES("586","HOLLOW/BOX CHISEL");
INSERT INTO item_tbl VALUES("587","HOOK");
INSERT INTO item_tbl VALUES("588","HOOK FOR K NAILS");
INSERT INTO item_tbl VALUES("589","HOT AIR OVEN");
INSERT INTO item_tbl VALUES("590","HOT WATER BAGS");
INSERT INTO item_tbl VALUES("591","HOT WATER STERLIZER 12 INCH");
INSERT INTO item_tbl VALUES("592","HUMIDIFIER (FOR O2 FLOW METER)");
INSERT INTO item_tbl VALUES("593","HUMIDIFIER FISHER");
INSERT INTO item_tbl VALUES("594","HYDROGEN PEROXIDE");
INSERT INTO item_tbl VALUES("595","I P A");
INSERT INTO item_tbl VALUES("596","I P MAIN REGISTER");
INSERT INTO item_tbl VALUES("597","IC FILES");
INSERT INTO item_tbl VALUES("598","ICE CAPS");
INSERT INTO item_tbl VALUES("599","ICU/CASUALTY MAIN REGISTER");
INSERT INTO item_tbl VALUES("600","IMP TRAYS DEN TUBES");
INSERT INTO item_tbl VALUES("601","IMPRESSION STONE PKT");
INSERT INTO item_tbl VALUES("602","IMPRESSION TRAYS");
INSERT INTO item_tbl VALUES("603","IMPROIED IMP TRAYS");
INSERT INTO item_tbl VALUES("604","IMS TRAYS EDEN TUBES");
INSERT INTO item_tbl VALUES("605","INACULOTION LOOPS");
INSERT INTO item_tbl VALUES("606","INFUSION / SYRINGE PUMP STAND");
INSERT INTO item_tbl VALUES("607","INFUSION PUMP");
INSERT INTO item_tbl VALUES("608","INJECTION ROOM REGISTER");
INSERT INTO item_tbl VALUES("609","INSTRUMENT TROLLEY (2X4) (AF-88B)");
INSERT INTO item_tbl VALUES("610","INSTRUMENT TROLLEY-TWO TIER (AF-88)");
INSERT INTO item_tbl VALUES("611","INSUFFLATOR MACHINE WEGA 30L");
INSERT INTO item_tbl VALUES("612","INTAKE & OUTPUT CHARTS");
INSERT INTO item_tbl VALUES("613","INTELLIGENT TOURNIQUET-2001");
INSERT INTO item_tbl VALUES("614","ISLAND TABLE (3000Lx1500Wx750H)");
INSERT INTO item_tbl VALUES("615","ISLAND TABLE (6000Lx1500Wx900H)");
INSERT INTO item_tbl VALUES("616","IV POLE ");
INSERT INTO item_tbl VALUES("617","JSB STAIN");
INSERT INTO item_tbl VALUES("618","JUMBO FILTERS (WATER PLANT)");
INSERT INTO item_tbl VALUES("619","K NAIL REAMER CANNCELLOUES:10");
INSERT INTO item_tbl VALUES("620","K NAIL REAMER CANNCELLOUES:11");
INSERT INTO item_tbl VALUES("621","K NAIL REAMER CANNCELLOUES:12");
INSERT INTO item_tbl VALUES("622","K NAIL REAMER CANNCELLOUES:6");
INSERT INTO item_tbl VALUES("623","K NAIL REAMER CANNCELLOUES:7");
INSERT INTO item_tbl VALUES("624","K NAIL REAMER CANNCELLOUES:8");
INSERT INTO item_tbl VALUES("625","K NAIL REAMER CANNCELLOUES:9");
INSERT INTO item_tbl VALUES("626","K NAIL REAMER CANNULATED FOR HUMURES:6");
INSERT INTO item_tbl VALUES("627","K NAIL REAMER CANNULATED FOR HUMURES:7");
INSERT INTO item_tbl VALUES("628","K NAIL REAMER CANNULATED FOR HUMURES:8");
INSERT INTO item_tbl VALUES("629","K NAIL REAMER CANNULATED:10");
INSERT INTO item_tbl VALUES("630","K NAIL REAMER CANNULATED:11");
INSERT INTO item_tbl VALUES("631","K NAIL REAMER CANNULATED:12");
INSERT INTO item_tbl VALUES("632","K NAIL REAMER CANNULATED:13");
INSERT INTO item_tbl VALUES("633","K NAIL REAMER CANNULATED:9");
INSERT INTO item_tbl VALUES("634","K WIRE 6 INCH 3.0MM");
INSERT INTO item_tbl VALUES("635","K WIRE BENDAR");
INSERT INTO item_tbl VALUES("636","K WIRE BENDER / CUTTER/ PLIER SMALL");
INSERT INTO item_tbl VALUES("637","K WIRE BENDER/CUTTER/PLIER(3 IN 1):BIG");
INSERT INTO item_tbl VALUES("638","K WIRE CUTTER");
INSERT INTO item_tbl VALUES("639","K WIRE: 1.0 MM");
INSERT INTO item_tbl VALUES("640","K WIRE:1.5 MM");
INSERT INTO item_tbl VALUES("641","K WIRE:1.8 MM");
INSERT INTO item_tbl VALUES("642","K WIRE:2.0 MM");
INSERT INTO item_tbl VALUES("643","K WIRE:2.5 MM");
INSERT INTO item_tbl VALUES("644","K WIRE:2.5 MM");
INSERT INTO item_tbl VALUES("645","KELLYS RETRACTOR BIG");
INSERT INTO item_tbl VALUES("646","KERISON/LAMINECTOMY PUNCH DOWNWARD 2,3,4,5,6M");
INSERT INTO item_tbl VALUES("647","KERISON/LAMINECTOMY PUNCH UPWARD 2,3,4,5,6MM");
INSERT INTO item_tbl VALUES("648","KERRISON PUNCH (DOWNWARD):45-5MM");
INSERT INTO item_tbl VALUES("649","KEY BOARD WOODEN");
INSERT INTO item_tbl VALUES("650","KIDNEY TRAY 10 INCH");
INSERT INTO item_tbl VALUES("651","KIDNEY TRAY 8 INCH");
INSERT INTO item_tbl VALUES("652","KIDNEY TRAYS PLASTIC");
INSERT INTO item_tbl VALUES("653","KIDNEY TRAYS STEEL SMALL");
INSERT INTO item_tbl VALUES("654","KILNER SKIN RETRACTORES (CAT PAW) DOUBLE ENDE");
INSERT INTO item_tbl VALUES("655","KNEE HAMMER");
INSERT INTO item_tbl VALUES("656","KNOT PUSHER");
INSERT INTO item_tbl VALUES("657","KOUCHER 8 INCH CURVED");
INSERT INTO item_tbl VALUES("658","KOUCHER 8 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("659","L SHAPE WALL TABLE (1650+1800)L X 450W X 750H");
INSERT INTO item_tbl VALUES("660","L SHAPE WALL TABLE (2400+1800)L X 450W X 750H");
INSERT INTO item_tbl VALUES("661","L SHAPE WALL TABLE (2400+1800)L X 750W X 750H");
INSERT INTO item_tbl VALUES("662","L SHAPE WALL TABLE (3000+12250)Lx750Wx900H)");
INSERT INTO item_tbl VALUES("663","L-MOULDS");
INSERT INTO item_tbl VALUES("664","LA BOTTLE (SPRAY)");
INSERT INTO item_tbl VALUES("665","LAB DISPATCH REGISTER");
INSERT INTO item_tbl VALUES("666","LAB/ICU/CASUALTY REGISTER");
INSERT INTO item_tbl VALUES("667","LAB/IP MAIN LONG REGISTER");
INSERT INTO item_tbl VALUES("668","LAB/OP MAIN REGISTER");
INSERT INTO item_tbl VALUES("669","LABLIN STICKER");
INSERT INTO item_tbl VALUES("670","LACKSELIRONGEUR DOUBLE ACTION");
INSERT INTO item_tbl VALUES("671","LAMINACTOMY RETRACTOR SELF LOCKING HARISH TYP");
INSERT INTO item_tbl VALUES("672","LAMINACTOMY RETRACTOR WITH FOLLOW OF BLADES 1");
INSERT INTO item_tbl VALUES("673","LANGE BACK RETRACTOR");
INSERT INTO item_tbl VALUES("674","LANGEN BACK LARGE");
INSERT INTO item_tbl VALUES("675","LANGEN BACK MEDIUM");
INSERT INTO item_tbl VALUES("676","LANGEN BACK SMALL");
INSERT INTO item_tbl VALUES("677","LAPRASCOPE TROLLEY ");
INSERT INTO item_tbl VALUES("678","LARYNGO SCOPE ADULT");
INSERT INTO item_tbl VALUES("679","LARYNGO SCOPE PAEDIATRIC");
INSERT INTO item_tbl VALUES("680","LENGEN BACK RECTROR 1 1/2 INCH");
INSERT INTO item_tbl VALUES("681","LENGEN BACK RECTROR 1 INCH");
INSERT INTO item_tbl VALUES("682","LENGEN BACK RECTROR 1/2 INCH");
INSERT INTO item_tbl VALUES("683","LENGEN BACK RECTROR 2 INCH");
INSERT INTO item_tbl VALUES("684","LENGEN BACK RECTROR 4 INCH");
INSERT INTO item_tbl VALUES("685","LENSMETER CL-300 TOPCON COMPUTERISED");
INSERT INTO item_tbl VALUES("686","LESMAN STAIN SOLUTION");
INSERT INTO item_tbl VALUES("687","LIGHT SORUCE X8000 STRYKER");
INSERT INTO item_tbl VALUES("688","LINEN TROLLEY (AF-99)");
INSERT INTO item_tbl VALUES("689","LIST OF CASES POSTED FOR OPERATION");
INSERT INTO item_tbl VALUES("690","LOOP HOLDERS");
INSERT INTO item_tbl VALUES("691","LOWER MOLAR FORCEPS (SET OF 12 NOS)");
INSERT INTO item_tbl VALUES("692","LOWMAN BONE CLAMPES DOUBLE JAW MEDIUM");
INSERT INTO item_tbl VALUES("693","M-SEAL");
INSERT INTO item_tbl VALUES("694","MACINTOSH (RUBBER)");
INSERT INTO item_tbl VALUES("695","MACKONY AGAR");
INSERT INTO item_tbl VALUES("696","MAESTROID RETRACTOR");
INSERT INTO item_tbl VALUES("697","MAGILL FORCEPS 10 INCH");
INSERT INTO item_tbl VALUES("698","MAGILLS FORCEPS 6 INCH");
INSERT INTO item_tbl VALUES("699","MAGILLS FORCEPS 8 INCH");
INSERT INTO item_tbl VALUES("700","MAIN OT REGISTER");
INSERT INTO item_tbl VALUES("701","MARKER CD");
INSERT INTO item_tbl VALUES("702","MARKER PERMANENT");
INSERT INTO item_tbl VALUES("703","MARKER WHITE BOARD");
INSERT INTO item_tbl VALUES("704","MARYLAND DISSTER");
INSERT INTO item_tbl VALUES("705","MATRIX STRIPS");
INSERT INTO item_tbl VALUES("706","MATTRESS - MULTI");
INSERT INTO item_tbl VALUES("707","MAVALTON TRIMING SET");
INSERT INTO item_tbl VALUES("708","MAYO INSTRUMENT TROLLEY (AF-93)");
INSERT INTO item_tbl VALUES("709","MAYO SCISSOR 6 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("710","MAYO SCISSOR 7 INCH CURVED");
INSERT INTO item_tbl VALUES("711","MAYO SCISSOR 7 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("712","MAYO SCISSOR 8 INCH CURVED");
INSERT INTO item_tbl VALUES("713","MAYO SCISSOR 8 INCH STRAIGHT");
INSERT INTO item_tbl VALUES("714","MAYOMA SCREW");
INSERT INTO item_tbl VALUES("715","MC DONALD DESSECTOR- DOUBLE ENDED");
INSERT INTO item_tbl VALUES("716","MEASUREMENT TAPE");
INSERT INTO item_tbl VALUES("717","MEASURING CYLENDER (1000ML)");





CREATE TABLE `master_backupdatabase` (
  `auto_number` int(255) NOT NULL AUTO_INCREMENT,
  `backupfilename` varchar(255) COLLATE latin1_general_ci NOT NULL,
  `backupfiledate` datetime NOT NULL,
  `username` varchar(255) COLLATE latin1_general_ci NOT NULL,
  `ipaddress` varchar(255) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`auto_number`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

INSERT INTO master_backupdatabase VALUES("12","DB_Backup_2014Oct20_164612.sql","2014-10-20 16:46:12","Ramana Reddy","192.168.1.77");
INSERT INTO master_backupdatabase VALUES("11","DB_Backup_2014Oct20_164601.sql","2014-10-20 16:46:01","Ramana Reddy","192.168.1.77");





CREATE TABLE `purchase_tbl` (
  `sno` int(15) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(15) NOT NULL,
  `item_id` int(15) NOT NULL,
  `unit_id` int(15) NOT NULL,
  `unitsreceived` int(15) NOT NULL,
  `noofitems` int(15) NOT NULL,
  `billno` varchar(200) NOT NULL,
  `billdate` varchar(25) NOT NULL,
  `rcvcno` varchar(200) NOT NULL,
  `rcdate` varchar(25) NOT NULL,
  PRIMARY KEY (`sno`),
  KEY `supplier_id` (`supplier_id`),
  KEY `item_id` (`item_id`),
  KEY `unit_id` (`unit_id`),
  CONSTRAINT `purchase_tbl_ibfk_1` FOREIGN KEY (`supplier_id`) REFERENCES `supplier_tbl` (`supplier_id`),
  CONSTRAINT `purchase_tbl_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `item_tbl` (`item_id`),
  CONSTRAINT `purchase_tbl_ibfk_3` FOREIGN KEY (`unit_id`) REFERENCES `unit_tbl` (`unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






CREATE TABLE `stocks_tbl` (
  `sno` int(15) NOT NULL AUTO_INCREMENT,
  `item_id` int(15) NOT NULL,
  `unit_id` int(15) NOT NULL,
  `unitsissued` int(5) NOT NULL,
  `quantity` int(5) NOT NULL,
  PRIMARY KEY (`sno`),
  KEY `item_id` (`item_id`),
  KEY `unit_id` (`unit_id`),
  CONSTRAINT `stocks_tbl_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `item_tbl` (`item_id`),
  CONSTRAINT `stocks_tbl_ibfk_2` FOREIGN KEY (`unit_id`) REFERENCES `unit_tbl` (`unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






CREATE TABLE `supplier_tbl` (
  `supplier_id` int(15) NOT NULL AUTO_INCREMENT,
  `supplier_name` varchar(200) NOT NULL,
  `supplier_address` varchar(500) NOT NULL,
  `supplier_mobile` varchar(15) NOT NULL,
  PRIMARY KEY (`supplier_id`)
) ENGINE=InnoDB AUTO_INCREMENT=90 DEFAULT CHARSET=latin1;

INSERT INTO supplier_tbl VALUES("4","Sample","Vijayawada","0866 2573542");
INSERT INTO supplier_tbl VALUES("5","AFFORD MEDICAL TECHNOLOGIES PVT LTD","B 230 2ND MAIN ROAD,<br />/\n/SAINIKPURI,<br />/\n/SECUNDERABAD,<br />/\n/TELANGANA STATE","9030011040");
INSERT INTO supplier_tbl VALUES("6","IKON MEDICAL SYSTEMS-VIJAYAWADA","H.NO. 29/28/1/9,<br />/\n/KOVELAMUDIVARI STREET,<br />/\n/SURYARAOPET,<br />/\n/VIJAYAWADA- 520 002","9177333713");
INSERT INTO supplier_tbl VALUES("7","SOUTH INDIA ENTERPRISES","4-3-563/4,NEAR ENDOWMENT OFFICE,<br />/\n/TILAK ROAD, ABINDS,<br />/\n/HYDERABAD-500001","9848068041");
INSERT INTO supplier_tbl VALUES("8","AVISHKAR DENTAL SCIENTIFIC & SURGICALS","4-3-560/2<br />/\n/BOGGULAKUNTA X ROADS,<br />/\n/ADJ.MAHAVIR AUTO MART,<br />/\n/TILAK ROAD, ABIDS,<br />/\n/HYD-1","9885554403");
INSERT INTO supplier_tbl VALUES("9","T.T.SUPER BAZAR","12-2-822/B,<br />/\n/MEHDIPATNAM,<br />/\n/BELOW NIIT,<br />/\n/HYD","040 66465045");
INSERT INTO supplier_tbl VALUES("10","THE SURGICAL TRADING CO.","5-4-457, <br />/\n/NAMPALLY STATION ROAD,<br />/\n/HYDERABAD-500 001","040 24613534");
INSERT INTO supplier_tbl VALUES("11","NIMRA INSTITUTE OF MEDICAL SCIENCES","4-90, NIMRA NAGAR,<br />/\n/JUPUDI (V),<br />/\n/IBRAHIMPATNAM (M),<br />/\n/KRISHNA DIST","0866 6545454");
INSERT INTO supplier_tbl VALUES("12","DECCAN DENTAL DEPOT PVT.LTD.,","24, SRI RAMA TOWERS,<br />/\n/TILAK ROAD, ABIDS,<br />/\n/HYDERABAD- 500 001","09949992186");
INSERT INTO supplier_tbl VALUES("13","AMAN SCIENTIFIC PRODUCTS","17-15-25, NADAR STREET,<br />/\n/MASJEED CENTRE,<br />/\n/PEZZONIPET,<br />/\n/VIJAYAWADA -3","9290117053");
INSERT INTO supplier_tbl VALUES("14","SHRIRAM OFFSET PRINTERS","28-7-6,<br />/\n/SK.MOHIDDIN STREET,<br />/\n/ARUNDELPET,<br />/\n/VIJAYAWADA-520 002","9849137040");
INSERT INTO supplier_tbl VALUES("15","METRO CASH & CARRY INDIA PVT. LTD.","SURVEY NO.25,<br />/\n/MOGALRAJPURAM,<br />/\n/VIJAYAWADA -520 010","0866 6768000");
INSERT INTO supplier_tbl VALUES("16","BALAJI RUMMAGE LIQUIDS & HOUSE KEEPING TOOLS","57-14-1A,<br />/\n/NEAR SBI BANK,<br />/\n/PANTAKALUVA ROAD,<br />/\n/PATAMATA, VJA -10","9291525253");
INSERT INTO supplier_tbl VALUES("17","RAMA VILAS GENERAL STORES","V.T.P.S. ROAD,<br />/\n/IBRAHIMPATNAM-521 456","0866 2882257");
INSERT INTO supplier_tbl VALUES("18","SRI BHUVANESWARI SCIENTIFIC & SURGICAL","29-5-1/11,<br />/\n/CHERUKUPALLI VARI STREET,<br />/\n/GOVERNERPETA,<br />/\n/VIJAYAWADA 502 002","9246415386");
INSERT INTO supplier_tbl VALUES("19","LATHA MEDICAL AGENCIES","29-10-1/2 & 1/3, UPSTAIRS,<br />/\n/NARASIMHARAO NAIDU STREET,<br />/\n/OPP. PRUNIMA MEDICALS,<br />/\n/SURYARAOPET,<br />/\n/VJA-2","9849307559");
INSERT INTO supplier_tbl VALUES("20","SRI RAMDEV ENTERPRISES","11-40-17,<br />/\n/PULIPATIVARI STREET,<br />/\n/VJA-1","0866 2424880");
INSERT INTO supplier_tbl VALUES("21","HRINKAR HANKIES","11-40-9, SHOP NO.2,<br />/\n/PULIPATIVARI STREET,<br />/\n/VIJAYAWADA-1","9603641755");
INSERT INTO supplier_tbl VALUES("22","KRISHNA COMPUTER PERIPHERALS","SHOP NO.50,<br />/\n/N.T.R.SHOPPING COMPLEX,<br />/\n/VIJAYAWADA-2","9246476588");
INSERT INTO supplier_tbl VALUES("23","RAJEEV CERAMICS","HYDERABAD","040 66611442");
INSERT INTO supplier_tbl VALUES("24","FRESH IDEAS","26-13-56,<br />/\n/GALLA VARI STREET,<br />/\n/OPP.HOTEL ILAPURAM,<br />/\n/GANDHINAGAR,<br />/\n/VJA-3","8977181554");
INSERT INTO supplier_tbl VALUES("25","IMPERIAL WATCH COMPANY","PARK ROAD,<br />/\n/VIJAYAWADA-520 001.","0866 2567740");
INSERT INTO supplier_tbl VALUES("26","RENU ENTERPRISES","NEW DELHI -15","011");
INSERT INTO supplier_tbl VALUES("27","VIJAYALAKSHMI STATIONERY","11-40-12,<br />/\n/PULIPATIVARI STREET,<br />/\n/VIJAYAWADA 520 001.","0866 6622343");
INSERT INTO supplier_tbl VALUES("28","SAI DURGA GLASS TRADERS","27-37-143/144,<br />/\n/NEAR MANORAMA HOTEL,<br />/\n/GOVERNERPET,<br />/\n/VJA-2","9246402446");
INSERT INTO supplier_tbl VALUES("29","DHANALAXMI AGENCIES","11-31-2/5,<br />/\n/PARK ROAD,<br />/\n/VIJAYAWADA-1","0866 2425817");
INSERT INTO supplier_tbl VALUES("30","ROYAL SURGICALS","29-4-26,<br />/\n/KODANDARAMIREDDY STREET,<br />/\n/VIJAYAWADA-2","0866 2439995");
INSERT INTO supplier_tbl VALUES("31","SAFENVIRON","29-3-14,<br />/\n/VENKATESWARA RAO STREET,<br />/\n/GOVERNERPET, VJA-2.","0866 2433355");
INSERT INTO supplier_tbl VALUES("32","VISHNU SURGICALS","29-6-6/1, <br />/\n/NAKKAL ROAD,<br />/\n/BESIDE CENTRAL BANK,<br />/\n/SURYARAOPET,<br />/\n/VJA-2","9440492189");
INSERT INTO supplier_tbl VALUES("33","S.R.S SURGICALS & SCIENTIFIC","28-24-6B,<br />/\n/HUSSAIN SAHEB STREET,<br />/\n/ARUNDELPET,<br />/\n/VJA-2","9032009786");
INSERT INTO supplier_tbl VALUES("34","SRINIVASA AQUA SYSTEMS","12-2-280/2, BRP ROAD,<br />/\n/OPP. POLICE QUARTERS,<br />/\n/VJA-1","9703230658");
INSERT INTO supplier_tbl VALUES("35","SRI ANJANEYA ENTERPRISES","RING CENTRE,<br />/\n/VTPS ROAD,<br />/\n/IBRAHIMPATNAM,<br />/\n/VJA-521 456","0866 2881957");
INSERT INTO supplier_tbl VALUES("36","SONOVISION","ELURU ROAD,<br />/\n/VJA-2","0866 6641110");
INSERT INTO supplier_tbl VALUES("37","BHAVANI STATIONERY MART","11-40-164,<br />/\n/PULIPATIVARI STREET,<br />/\n/VJA-1","9390036017");
INSERT INTO supplier_tbl VALUES("38","VTPS OCC STORES","IBRAHIMPATNAM,<br />/\n/VJA-521 456,<br />/\n/KRISHNA DIST.","0866 2882468");
INSERT INTO supplier_tbl VALUES("39","APOLLO SURGICALS","29-6-29,<br />/\n/RAMACHANDRA RAO ROAD,<br />/\n/SURYARAOPET,<br />/\n/VJA-2","0866 6622555");
INSERT INTO supplier_tbl VALUES("40","VARDHAMAN HARDWARE AND KITCHEN","11-62-96,97<br />/\n/NEAR GANESH TEMPLE,<br />/\n/CANAL ROAD,<br />/\n/VJA-1","9849858587");
INSERT INTO supplier_tbl VALUES("41","SRI VENKATESWARA PLASTICS","11-60/2-15,<br />/\n/VAIZULLAVARI STREET,<br />/\n/NEAR PULIPATIVARI STREETS,<br />/\n/VJA-1","0866 2422111");
INSERT INTO supplier_tbl VALUES("42","VIJAY ENTERPRISES","11-40-21,<br />/\n/PULIPATIVARI STREET,<br />/\n/VJA-1","0866 6699515");
INSERT INTO supplier_tbl VALUES("43","SITA SURGICALS","29-4-54K,<br />/\n/CSI SHOPPING COMPLEX,<br />/\n/OPP. DOPHIN DIAGNOSTICS,<br />/\n/NAKKALA ROAD,<br />/\n/VJA-2","9247067899");
INSERT INTO supplier_tbl VALUES("44","WELDEN HEALTH CARE","40-9-79, SAI NAGAR,<br />/\n/BEHIND: BAKERS INN,<br />/\n/BENZ CIRCLE,<br />/\n/VJA-10","08885580058");
INSERT INTO supplier_tbl VALUES("45","CARDIO CONSUMABLES PVT LTD","2-3-512/D, BAPU NAGAR,<br />/\n/AMBERPET,<br />/\n/HYDERABAD-13","9396444722");
INSERT INTO supplier_tbl VALUES("46","ANDHRA SAFE COMPANY","27-1-30,<br />/\n/M.G. HOUSE,<br />/\n/ELURU ROAD,<br />/\n/VJA-2","9908720786");
INSERT INTO supplier_tbl VALUES("47","M.S. ENTERPRISES","28-19-2/1,<br />/\n/MOHD YASEEN STREET,<br />/\n/ARUNDELPET,<br />/\n/VJA-2","0866 2442786");
INSERT INTO supplier_tbl VALUES("48","JAGRUTI LAPTOPS & COMPUTERS","SHOP NO.44,<br />/\n/N.T.R.COMPLEX,<br />/\n/GOVERNERPET,<br />/\n/VJA-2","9246464701");
INSERT INTO supplier_tbl VALUES("49","VARUNI SURGICALS","29-5-14a,<br />/\n/CHERUKUPALLI VARI STREET,<br />/\n/GOVERNERPET,<br />/\n/VJA-2","9912189301");
INSERT INTO supplier_tbl VALUES("50","ORIENT MEDI SYSTEMS","54-20/4-19,<br />/\n/KANAKADURGA GAZETTED OFFICERS COLONY,<br />/\n/GURUNANAK ROAD,<br />/\n/VJA-8","9676853444");
INSERT INTO supplier_tbl VALUES("51","MEGHANA SURGICALS & CO.","2-2-1136/7,<br />/\n/NEW NALLKUNTA,<br />/\n/HYDERABAD- 500 044","9849321132");
INSERT INTO supplier_tbl VALUES("52","SRI SAI WATCH CENTRE","29-37-140, ELURU ROAD,<br />/\n/NEAR RAMA MANDIRAM,<br />/\n/VJA-2","0866 6622524");
INSERT INTO supplier_tbl VALUES("53","BHARATI SHOE CENTRE","ELURU ROAD,<br />/\n/VJA-2","0866");
INSERT INTO supplier_tbl VALUES("54","RAMU CHEMICALS","M.M.ROAD,<br />/\n/MANGAMUR- 523 225,<br />/\n/PRAKASAM DIST","9703377168");
INSERT INTO supplier_tbl VALUES("55","MEHRA EYETECH PRIVATE LIMITED","NO. 22, MAIN ROAD,<br />/\n/SAKTHI NAGAR,<br />/\n/PUDUCHERRY-605 013,<br />/\n/INDIA.","0413 2248354");
INSERT INTO supplier_tbl VALUES("56","NAVOADAYA PALSTIC CENTRE","11-42-14,<br />/\n/RAMGOPAL STREET,<br />/\n/VJA-1","0866 2423591");
INSERT INTO supplier_tbl VALUES("57","PHANI GREESHMA AGENCIES","SHOP NO. 71-2-1,<br />/\n/N.S.M.SCHOOL ROAD,<br />/\n/PATAMATA,<br />/\n/VJA-10","9440508161");
INSERT INTO supplier_tbl VALUES("58","SRI SRINIVASA GENRAL STORES","RING CENTRE,<br />/\n/IBRAHIMPATNAM,<br />/\n/VJA-521 456","0866 2883772");
INSERT INTO supplier_tbl VALUES("59","DENTAL PARADISE","20, GROUND FLOOR,<br />/\n/MINERVA COMPLEX,<br />/\n/S.D. ROAD,<br />/\n/SECUNDERABAD-3","8885580058");
INSERT INTO supplier_tbl VALUES("60","RAHEM TAILORS","RING CENTRE,<br />/\n/IBRHIMPATNAM","0866");
INSERT INTO supplier_tbl VALUES("61","B.L. TEXTILES","D.NO.27-15-152,<br />/\n/OPP. V.H.R. COMPLEX,<br />/\n/BESANT ROAD,<br />/\n/VJA-2","9392123975");
INSERT INTO supplier_tbl VALUES("62","VARSHINI COMPUTERS","OPP. SRINIVASA ELECTRONICS,<br />/\n/BESIDE VIJAYA BANK,<br />/\n/SESHADRI SASTRY ST.<br />/\n/VJA-2","9948830995");
INSERT INTO supplier_tbl VALUES("63","FUJIFILM INDIA PVT LTD","63/4,<br />/\n/SY NO.157,158,159,<br />/\n/KOMPALLY,<br />/\n/SECUNDERABAD-14","9177333713");
INSERT INTO supplier_tbl VALUES("64","CITY POWER POINT","3-6-656,<br />/\n/GOUND FLOOR,<br />/\n/STREET NO.9,<br />/\n/HIMAYATHNAGAR,<br />/\n/HYD-29","040 32445599");
INSERT INTO supplier_tbl VALUES("65","VAISHNO DEVI TRADERS","9-4-84/146,<br />/\n/KAKATIYA NAGAR,<br />/\n/HYDERABAD-8","040 23510408");
INSERT INTO supplier_tbl VALUES("66","SRINIVASA MEDICAL & IMAGING PRODUCTS PVT LTD","29-3-19,<br />/\n/VENKATESWARARAO STREET,<br />/\n/OPP. APCO BHAVAN,<br />/\n/GOVERNERPET,<br />/\n/VJA-2","9849081318");
INSERT INTO supplier_tbl VALUES("67","MODERN LAB DEVELOPING SCIENCE & TECHNOLOGY","109, G.N. CHETTY ROAD,<br />/\n/T. NAGAR, <br />/\n/CHANNEI - 600 017","044 28346444");
INSERT INTO supplier_tbl VALUES("68","SRI KARTHIKEYA PHARMA","28-25-37,<br />/\n/NASURULLAH KHAN STREET,<br />/\n/ARUNDELPET.<br />/\n/VJA-2","9246786477");
INSERT INTO supplier_tbl VALUES("69","SRI LAKSHMI PEDMAVATHI FANCY & GENERAL STORES","VIJAYASAI TOWERS,<br />/\n/RING CENTRE.<br />/\n/IBARHIMPTANAM","0866");
INSERT INTO supplier_tbl VALUES("70","SRI VENKATESWARA AGENCIES PVT LTD","29-7-41,<br />/\n/FLAT NO.2,<br />/\n/VISHNUVARDHAN RAO STREET,<br />/\n/SURYARAOPET,<br />/\n/VJA-2","0866 2438537");
INSERT INTO supplier_tbl VALUES("71","MAGNUM GRAPHICS","3-5-781/A/8,<br />/\n/NEAR St. JOSEPH SCHOOL,<br />/\n/KING KOTI,<br />/\n/HYDERABAD-29","040 23232357");
INSERT INTO supplier_tbl VALUES("72","BHARAT SURGICALS","11-31-16,<br />/\n/PARK ROAD,<br />/\n/VJA-1","9848264946");
INSERT INTO supplier_tbl VALUES("73","ADAMS YASMEEN WATCH CO","28-1-62,<br />/\n/ELURU ROAD,<br />/\n/VJA-2","0866 6662479");
INSERT INTO supplier_tbl VALUES("74","DURGA BHAVANI ENTERPRISES","11-43-1,<br />/\n/YANDURIVARI STREET,<br />/\n/VJA-1","0866 2426114");
INSERT INTO supplier_tbl VALUES("75","SRI BALAJI GOODWILL","OPP: MANDAL OFFICE,<br />/\n/IBRAHIMPATNAM","0866 883111");
INSERT INTO supplier_tbl VALUES("76","POPULAR SHOE MART","GANDHINAGAR,<br />/\n/VJA-3","0866");
INSERT INTO supplier_tbl VALUES("77","M/S. APNA BAZAR VSM GENERAL STORES","DIVYA COMPLEX,<br />/\n/IBRAHIMPATNAM- 521 456","9885122488");
INSERT INTO supplier_tbl VALUES("78","SRI PRASAD ELECTRICALS","28-1-52,<br />/\n/ELURU ROAD,<br />/\n/NEAR RAMA MANDIRAM,<br />/\n/VJA-2","0866 6667769");
INSERT INTO supplier_tbl VALUES("79","CURA HEALTHCARE PRIVATE LIMITED","40-5-15, GROUND FLOOR,<br />/\n/TIKKAL ROAD,<br />/\n/D.V MANOR LANE,<br />/\n/LABBIPET, VJA-10","0866");
INSERT INTO supplier_tbl VALUES("80","GELLIS JUTE FIRM","MAIN ROAD,<br />/\n/VJA-1","0866 2423940");
INSERT INTO supplier_tbl VALUES("81","SREE AMBIKA STATIONERS","11-40-154/5,<br />/\n/PULIPATIVARI STREET,<br />/\n/VJA-1","0866 2423450");
INSERT INTO supplier_tbl VALUES("82","SREE VENKATESWARA VASTRALAYAM","SHOP NO.47,<br />/\n/VASTRALATHA,<br />/\n/VJA-1","9848732339");
INSERT INTO supplier_tbl VALUES("83","SHADAN HOSPITAL  HYD","HYDERABAD","040");
INSERT INTO supplier_tbl VALUES("84","CARETECH SYSTEMS","16-11-511/D/374,<br />/\n/SHALIVAHANA NAGAR,<br />/\n/MOOSARAMBAGH,<br />/\n/HYDERABAD-60","9849048358");
INSERT INTO supplier_tbl VALUES("85","SWASTIK TRADERS","3-4-207/4, 1St FLOOR,<br />/\n/KAILASH MARKET,<br />/\n/TOBACCO BAZAR,<br />/\n/SECUNDERABAD-3","9848034448");
INSERT INTO supplier_tbl VALUES("86","M/S. R. D. PLAST PVT. LTD.","A-13/3,<br />/\n/NARAINA INDUSTRIAL AREA,<br />/\n/PHASE-1,<br />/\n/NEW DELHI- 110028","011 25891485");
INSERT INTO supplier_tbl VALUES("87","NIPUN SAFETY EQUIPMENTS & SOLUTIONS","401,GAYATHRI TOWERS,<br />/\n/GREEN HILLS COLONY,<br />/\n/KOTHAPET,<br />/\n/HYDERABAD-35","9985650449");
INSERT INTO supplier_tbl VALUES("88","RAHAMAN FURNITURE WORKS","25-15-109,<br />/\n/G.S.RAJU ROAD,<br />/\n/SATYANARAYANAPURAM,<br />/\n/VJA-11","9440137481");
INSERT INTO supplier_tbl VALUES("89","CARRIER AIRCONDITIONING & REFRIGERATION LIMITED","CARRIER COMPLEX,<br />/\n/NARSINGPUR,<br />/\n/KHERKI DAULA POST,<br />/\n/DELHI-JAIPUR HIGHWAY,<br />/\n/GURGAON- 122 001","0124 4825500");





CREATE TABLE `unit_tbl` (
  `unit_id` int(15) NOT NULL AUTO_INCREMENT,
  `unit_name` varchar(200) NOT NULL,
  `quantity` int(15) NOT NULL,
  PRIMARY KEY (`unit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;






CREATE TABLE `user_tbl` (
  `user_id` int(15) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(100) NOT NULL,
  `user_password` varchar(200) NOT NULL,
  `role` int(2) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

INSERT INTO user_tbl VALUES("1","Ramana Reddy","f9209b7866c9f69823201c1732cc8645","2");
INSERT INTO user_tbl VALUES("2","Ismail","f3b32717d5322d7ba7c505c230785468","3");
INSERT INTO user_tbl VALUES("3","Zubair","08fc70b4b9916f75309d7c0c9a4f5237","4");



